

show databases;
create database Enterprise_System;

CREATE TABLE `Enterprise_System`.`manager` (
  `MANAGER_CODE` INT NOT NULL,
  `MANAGER_FNAME` VARCHAR(45) NOT NULL,
  `MANAGER_LNAME` VARCHAR(45) NOT NULL,
  `MANAGER_AREACODE` VARCHAR(3) NOT NULL,
  `MANAGER_EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MANAGER_CODE`));
  
CREATE TABLE `Enterprise_System`.`department` (
  `DEPT_NUM` INT NOT NULL,
  `DEPT_NAME` VARCHAR(45) NOT NULL,
  `MANAGER_CODE` INT NULL,
  PRIMARY KEY (`DEPT_NUM`),
  INDEX `MANAGER_CODE_idx` (`MANAGER_CODE` ASC) VISIBLE,
  CONSTRAINT `MANAGER_CODE`
    FOREIGN KEY (`MANAGER_CODE`)
    REFERENCES `Enterprise_System`.`manager` (`MANAGER_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    
CREATE TABLE `Enterprise_System`.`employee` (
  `EMP_NUM` INT NOT NULL,
  `EMP_FNAME` VARCHAR(45) NOT NULL,
  `EMP_LNAME` VARCHAR(45) NOT NULL,
  `EMP_AREACODE` VARCHAR(3) NULL,
  `EMP_EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EMP_NUM`));

CREATE TABLE `Enterprise_System`.`expense_report` (
  `EXP_REPORT_NUM` INT NOT NULL,
  `EMP_NUM` INT NOT NULL,
  `EXP_REPORT_DATE` DATETIME NOT NULL,
  `EXP_REPORT_TOTAL` INT NOT NULL,
  `EXP_REPORT_STATUS` VARCHAR(45) NULL,
  PRIMARY KEY (`EXP_REPORT_NUM`, `EMP_NUM`),
  INDEX `EMP_CODE_idx` (`EMP_NUM` ASC) VISIBLE,
  CONSTRAINT `EMP_NUM`
    FOREIGN KEY (`EMP_NUM`)
    REFERENCES `Enterprise_System`.`employee` (`EMP_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `Enterprise_System`.`expense_item` (
  `EXP_ITEM_NUM` INT NOT NULL,
  `EMP_CODE` INT NOT NULL,
  `EXP_ITEM_DATE` DATETIME NOT NULL,
  `EXP_ITEM_AMOUNT` INT NOT NULL,
  PRIMARY KEY (`EXP_ITEM_NUM`, `EMP_CODE`),
  INDEX `EMP_CODE_idx` (`EMP_CODE` ASC) VISIBLE,
  CONSTRAINT `EMP_CODE`
    FOREIGN KEY (`EMP_CODE`)
    REFERENCES `Enterprise_System`.`employee` (`EMP_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EXP_ITEM_NUM`
    FOREIGN KEY (`EXP_ITEM_NUM`)
    REFERENCES `Enterprise_System`.`category` (`EXP_ITEM_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE `Enterprise_System`.`category` (
  `EXP_ITEM_NUM` INT NOT NULL,
  `EXP_ITEM_DESCRIPTION` VARCHAR(45) NOT NULL,
  `EXP_ITEM_CATEGORY` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EXP_ITEM_NUM`));